### PR TITLE
Bump Gnome Platform version to 44

### PR DESCRIPTION
**Pull request by vdualb**

### CODE REVIEW

**Comment by Newbytee** [comment]
I think the problem is some outdated dependency not working with the newer Python version.

**Comment by vdualb** [comment]
i dont have any experience with python. help is appreciated

**Comment by Newbytee** [comment]
https://github.com/flathub/com.github.alexhuntley.Plots/pull/4 upgraded the GNOME Platform to 44. I think this can be closed.

**Comment by alexhuntley** [comment]
Closing, but thanks for the effort.

**Pull request closed without merging**
